<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <OutputType>WinExe</OutputType>
  <TargetFramework>net8.0-windows</TargetFramework>
  <UseWindowsForms>true</UseWindowsForms>
  <EnableWindowsTargeting>true</EnableWindowsTargeting>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <ApplicationIcon>app.ico</ApplicationIcon>
  <Product>K86 Light</Product>
  <AssemblyName>K86LayoutLight</AssemblyName>
</PropertyGroup>
<PropertyGroup>
  <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
  <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
  <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
</PropertyGroup>
<ItemGroup><EmbeddedResource Include="app.ico;en.ico;ru.ico" /></ItemGroup></Project>
